### PR TITLE
Refactor proposals into a separate Antora component

### PR DESCRIPTION
**Pull request by oddhack**
Per #54

This must be accepted along with https://github.com/KhronosGroup/Vulkan-Docs/pull/2358

If there are any xrefs from other components (guide, tutorials, samples, etc.) to proposal documents, those will also have to change to match the refactoring. The only one I see on quick inspection is on https://docs.vulkan.org/guide/latest/index.html and really, ought to be removed, refactoring or not - it serves no purpose and I think is just left over from something I put in when initially doing the site.

### CODE REVIEW

**Comment by oddhack** [comment]
N.b. this cannot pass CI until after both it and the Vulkan-Docs PR are merged into main. I have built locally and it is OK there.

**Comment by oddhack** [comment]
@tobski please check https://docs.vulkan.org/sandbox/spec/latest/index.html and see if this does what you had in mind (it will only be up until the next time I do a site update, then will get wiped out).

**Comment by Tobski** [comment]
> @Tobski please check https://docs.vulkan.org/sandbox/spec/latest/index.html and see if this does what you had in mind (it will only be up until the next time I do a site update, then will get wiped out).

Separating it out looks good, though I can't see a way to get to the proposals except via search at the moment?

**Comment by oddhack** [comment]
> Separating it out looks good, though I can't see a way to get to the proposals except via search at the moment?

I thought that was working, auggh. Have run into several weird arbitrary restrictions on refactoring a single repo into two components. When I sort that out it will be selectable in the lower-left popup menu like the other components, but would not merge this until that's sorted :-(

**Comment by oddhack** [comment]
Agreed to change the title to "Feature Descriptions" in site nav and component name (probably not in URLs) as part of this.

**Comment by oddhack** [comment]
Build has been verified locally and I've merged the underlying Vulkan-Docs PR to main in that repo, so will accept this as soon as it passes CI.

**Pull request merged**
